name: pytest

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: postgresuser
          POSTGRES_PASSWORD: postgrespassword
          PGPASSWORD: postgrespassword
          POSTGRES_DB: sqlalchemytest
          TZ: "Asia/Tokyo"
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install Dependencies
        working-directory: app
        run: poetry install --no-interaction

      - name: DB migration
        run: |
          make test-migrate
        env:
          DB_USER: postgresuser
          DB_PASS: postgrespassword
          DB_NAME: sqlalchemytest
          DB_HOST: postgres
          DB_PORT: 5432

      - name: Run Pytest
        working-directory: app
        run: make test-ci
        continue-on-error: true
        env:
          DB_USER: postgresuser
          DB_PASS: postgrespassword
          DB_NAME: sqlalchemytest
          DB_HOST: postgres
          DB_PORT: 5432

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./app/coverage/pytest-coverage.txt
          junitxml-path: ./app/coverage/pytest.xml
          hide-badge: false
          hide-report: false